POST http://localhost:3000
Content-Type: application/json

{
  "name": "Vingador", 
  "age": "190"
}

###

POST http://localhost:3000
Content-Type: application/json

{
  "name": "Vingador", 
  "age": "18"
}


###

POST http://localhost:3000
Content-Type: application/json

{
  "name": "Vi", 
  "age": "180"
}

###

POST http://localhost:3000
Content-Type: application/json

{
  "connectionError": "Vi"
}